### ISSUE TITLE
[Bug] "Hide Friends in Same Instance" hides players in unrelated private instances

### ISSUE THREAD

**Issue by TapGhoul** [vrcx-team/VRCX#1210]
**Describe the bug**
When in an instance, having "Hide Friends in Same Instance" checked hides all players in private instances, whether or not they are in your instance.
VRCX correctly shows which players are in your instance, even if they are on orange, so it seems it's just overly-aggressively hiding them.

**To Reproduce**
1. Open Settings -> Appearance -> Side panel
2. Enable "Group by Instance" and "Hide Friends in Same Instance"
3. Join a VRC instance with friends - if the instance is empty (unsure if populated with others) this will not reproduce.
4. Toggle "Hide Friends in Same Instance" and you will see unrelated friends in private instances will be hidden.

Note: if this doesn't work immediately, try refreshing the friends list via the refresh button at the top right of the sidebar to make the "Same Instance" section appear.

**Expected behavior**
Players in unrelated private instances should still be visible on the sidebar when "Hide Friends in Same Instance" is enabled

**Screenshots**
I'd rather not expose my friends list, this is easy and consistent to reproduce.

**What version you are running**
VRCX 2025.03.01

**Comment by CheezusCrisp** [comment]
I can confirm I am also experiencing this issue. I've noticed some people in my friendslist are not appearing in the side bar.

**Comment by Natsumi-sama** [comment]
I've pushed a nighly update that might fix this, give it a try and let me know, I haven't had time to test for the issue yet so I don't fully understand what is going on.

**Comment by TapGhoul** [comment]
It doesn't seem to be fixed on `VRCX Nightly 2025-05-01T14.14-8af450e` - When I join into an instance with more than one friend in, all private people disappear again. If the instance I'm in shows up under "Same Instance" then all private users disappear. It seems though if I am in an instance with only one friend, and so they don't show up under "same instance", they are correctly removed from the online list and only show up under same instance even if I'm in it - not sure if this was the case before.

One thing that may be a lead, but may also be a red herring - private users disappeared when someone was in an instance on orange on my friends list. I didn't ask them to switch so I don't know, but maybe that may be related?

**Comment by Natsumi-sama** [comment]
More fixes since last test, I hope this is fixed now.

**Comment by TapGhoul** [comment]
On stable, VRCX now no longer shows friends in the same instance at all, it acts as if everyone is in a different instance. Now, even when vrcx is able to see (via the API) that someone on green or orange is in my instance, it still shows as if they are in a separate private instance.

**Comment by TapGhoul** [comment]
This seems fixed as far as I can tell, good stuff.
